site_name: M3RG LAB MANUAL
theme: 'material'
site_url: https://web.iitd.ac.in/~krishnan/labmanual/

nav:
- M3RG LAB:
  - {Introduction: index.md}
- Molecular Dynamics:
  - {Introduction: md/index.md}
- Softwares:
  - LAMMPS: 
    - {Introduction: softwares/lammps/index.md}
  - Peridigm:
    - {Introduction: softwares/peridigm/index.md}
docs_dir: ./source

plugins:
  - search
  - table-reader

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - markdown.extensions.admonition
  - fontawesome_markdown
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - mathjax-config.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS-MML_HTMLorMML
